PhonebookUIApp/Models/UserData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PhonebookUIApp.Models
{
    public class UserData
    {
        public int  UserId{ get; set; }

        public string UserName { get; set; }
    }
}

PhonebookUIApp/Models/UserModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Web;

namespace PhonebookUIApp.Models
{
    public class UserModel
    {
        public List<UserData> Users { get; set; }

        public List<UserPhoneBookData> PhoneBook { get; set; }
        
        public UserData newUser { get; set; }

        public UserPhoneBook newPhonebookRecord { get; set; }

        public UserModel()
        {
            Users = new List<UserData>();
            PhoneBook = new List<UserPhoneBookData>();
        }

    }


    public class UserPhoneBookData
    {
        public UserData User { get; set; }

        public List<UserData> Contacts { get; set; }

    }
}

PhonebookUIApp/Models/UserPhoneBook.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PhonebookUIApp.Models
{
    public class UserPhoneBook
    {
        public int RecordId { get; set; }

        public int UserId { get; set; }
 
        public int ContactId { get; set; }

    }
}

PhonebookUIApp/Controllers/HomeController.cs
using DataAccessLayer;
using PhonebookUIApp.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhonebookUIApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            //SQL Server

            SQLDALManager manager = new SQLDALManager("dbConnKey");
            DataTable allUsers = manager.executeStoreProcedure("getAllUser");

            List<UserData> usersList = new List<UserData>();
            List<UserPhoneBookData> phoneBooks = new List<UserPhoneBookData>();


            foreach(DataRow row in allUsers.Rows)
            {
                UserData user = new UserData
                {
                    UserId = Convert.ToInt32(row["user_id"]),
                    UserName = row["user_name"].ToString()
                };
                
                usersList.Add(user);


                DataTable contacts = manager.executeStoreProcedure("getContacts", new List<SqlParameter> { new SqlParameter("@userId", Convert.ToInt32(row["user_id"]))});


                List<UserData> contcts = new List<UserData>();

                foreach(DataRow contact in contacts.Rows)
                {
                    contcts.Add(new UserData
                    {
                        UserId = Convert.ToInt32(contact["user_id"]),
                        UserName = contact["user_name"].ToString()
                    });
                }

                phoneBooks.Add(new UserPhoneBookData { User = user, Contacts = contcts });
            };


            UserModel model = new UserModel
            {
                Users = usersList,
                PhoneBook = phoneBooks
            };


                ////////////////------------------------------------------------------------------
                //List<UserData> dummyUser = new List<UserData>
                //{
                //    new UserData { UserId = 1, UserName = "Alice" },
                //    new UserData { UserId = 2, UserName = "Bob" },
                //    new UserData { UserId = 3, UserName = "Michel" }
                //};

                //List<UserPhoneBookData> dummyPhonebook = new List<UserPhoneBookData>
                //{
                //    new UserPhoneBookData { User = dummyUser[0], Contacts = new List<UserData> { dummyUser[1], dummyUser[2] } },
                //    new UserPhoneBookData { User = dummyUser[1], Contacts= new List<UserData> {dummyUser[0],dummyUser[2]}}
                //};


                //UserModel model2 = new UserModel
                //{
                //    Users = dummyUser,
                //    PhoneBook = dummyPhonebook

                //};
                ///////////////////////////////////////---------------------------------------------




                return View(model);
            }



        [HttpPost]
        public ActionResult Create(UserModel data)
        {
            SQLDALManager manager = new SQLDALManager("dbConnKey");
            manager.executeStoreProcedure("insertUser", new List<SqlParameter> { new SqlParameter("@userName", data.newUser.UserName) });
            return RedirectToAction("Index");
        }
    }
}

PhonebookUIApp/Controllers/PhoneBookController.cs
using DataAccessLayer;
using PhonebookUIApp.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhonebookUIApp.Controllers
{
    public class PhoneBookController : Controller
    {
        // GET: PhoneBook
        public ActionResult Index()
        {
            //SQL Server

            SQLDALManager manager = new SQLDALManager("dbConnKey");
            DataTable allUsers = manager.executeStoreProcedure("getAllUser");

            List<UserData> usersList = new List<UserData>();
            List<UserPhoneBookData> phoneBooks = new List<UserPhoneBookData>();


            foreach (DataRow row in allUsers.Rows)
            {
                UserData user = new UserData
                {
                    UserId = Convert.ToInt32(row["user_id"]),
                    UserName = row["user_name"].ToString()
                };

                usersList.Add(user);


                DataTable contacts = manager.executeStoreProcedure("getContacts", new List<SqlParameter> { new SqlParameter("@userId", Convert.ToInt32(row["user_id"])) });


                List<UserData> contcts = new List<UserData>();

                foreach (DataRow contact in contacts.Rows)
                {
                    contcts.Add(new UserData
                    {
                        UserId = Convert.ToInt32(contact["user_id"]),
                        UserName = contact["user_name"].ToString()
                    });
                }

                phoneBooks.Add(new UserPhoneBookData { User = user, Contacts = contcts });
            };


            UserModel model = new UserModel
            {
                ////Users = usersList,
                PhoneBook = phoneBooks
            };


            ////////////////------------------------------------------------------------------
            //List<UserData> dummyUser = new List<UserData>
            //{
            //    new UserData { UserId = 1, UserName = "Alice" },
            //    new UserData { UserId = 2, UserName = "Bob" },
            //    new UserData { UserId = 3, UserName = "Michel" }
            //};

            //List<UserPhoneBookData> dummyPhonebook = new List<UserPhoneBookData>
            //{
            //    new UserPhoneBookData { User = dummyUser[0], Contacts = new List<UserData> { dummyUser[1], dummyUser[2] } },
            //    new UserPhoneBookData { User = dummyUser[1], Contacts= new List<UserData> {dummyUser[0],dummyUser[2]}}
            //};


            //UserModel model2 = new UserModel
            //{
            //    Users = dummyUser,
            //    PhoneBook = dummyPhonebook

            //};
            ///////////////////////////////////////---------------------------------------------




            return View(model);
        }

        [HttpPost]
        public ActionResult Create (UserModel data)
        {
            SQLDALManager manager = new SQLDALManager("dbConnKey");
            manager.executeStoreProcedure("createUserPhoneBook", new List<SqlParameter>
            {
                new SqlParameter ("@userId", data.newPhonebookRecord.UserId),
                new SqlParameter ("@contactId", data.newPhonebookRecord.ContactId)
            });

            return RedirectToAction("Index");
        }
    }
}

PhonebookUIApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PhonebookUIApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PhonebookUIApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@using PhonebookUIApp.Models
@model UserModel

<div class="main">
    <div class="users">
        <p>User List</p>
        <ul class="usersList">
            @foreach (UserData user in Model.Users)
            {
                <li>User ID: @user.UserId, User Name: @user.UserName</li>

            }
        </ul>
    </div>

    

    <div class="action">
        <h2>Create New User</h2>
        @using (Html.BeginForm("Create", "Home", FormMethod.Post))
        {
            @Html.LabelFor(m => m.newUser.UserName)
            @Html.TextBoxFor(m => m.newUser.UserName)
            <input type="submit" value="Submit"/>
        }
        <h2>Update User</h2>
        <h2>Delete User</h2>
    </div>


    

</div>

PhonebookUIApp/Views/PhoneBook/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@using PhonebookUIApp.Models
@model UserModel


<h2>PhoneBook Record</h2>

<div class="phonebook">
    <p>phonebook</p>
    @foreach (UserPhoneBookData phonebook in Model.PhoneBook)
    {

        <ul class="phonebooklist">
            User Id: @phonebook.User.UserId, UserName: @phonebook.User.UserName
            @foreach (UserData contact in phonebook.Contacts)
            {
                <li>Contact Name: @contact.UserName</li>
            }

        </ul>
    }
</div>


<div class="action">
        <h4>Create new phone book record</h4>
        @using (Html.BeginForm("Create", "PhoneBook", FormMethod.Post))
        {
            @Html.LabelFor(m=>m.newPhonebookRecord.UserId)
            @Html.TextBoxFor(m=>m.newPhonebookRecord.UserId)

            @Html.LabelFor(m=>m.newPhonebookRecord.ContactId)
            @Html.TextAreaFor(m=>m.newPhonebookRecord.ContactId)

            <input type="submit" value="Submit"/>
        }

</div>

PhonebookUIApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PhoneBook UI", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Users", "Index", "Home")</li>
                    <li>@Html.ActionLink("PhoneBook", "Index", "PhoneBook")</li>
                   
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        @*<footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>